#!/usr/bin/env python

import gi
from gi.repository import Gtk

gi.require_version("Gtk", "3.0")


class Widget(Gtk.Window):
    def __init__(self):
        self.connect("destroy", Gtk.main_quit)

    def add_inner(self):
        Gtk.Window.__init__(self, title="Hello World")
        self.button = Gtk.Button(label="Click Here")
        self.button.connect("clicked", self.on_button_clicked)
        self.add(self.button)

    def on_button_clicked(self, widget):
        print("Hello World")


if __name__ == "__main__":
    # Display the widget.
    Widget().show_all()
    # Run the event loop.
    Gtk.main()
